const TEX = "https://cdn.jsdelivr.net/gh/jeromeetienne/threex.planets@master/images";

export const SUN = {
  id: "sun",
  name: "The Sun",
  texture: `${TEX}/sunmap.jpg`,
  type: "G-type main-sequence star",
  tagline: "The gravitational heart of the solar system.",
  color: "#ffb347",
  glow: "#ff8c32",
  diameterKm: 1_392_700,
  mass: "333,000 Earths",
  dayLength: "25 days (equator)",
  temperature: "5,500°C surface · 15,000,000°C core",
  moons: 0,
  distance: "0 AU",
  year: "—",
  gravity: "28 g",
  discovered: "Prehistoric",
  description:
    "A vast sphere of plasma that holds every planet, asteroid, and comet in its pull. Nuclear fusion in its core turns hydrogen into helium, releasing the light and heat that make life on Earth possible. It contains 99.8% of all mass in the solar system.",
  facts: [
    "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.",
    "A million Earths could fit inside it.",
    "The solar wind streams charged particles that sculpt planetary magnetospheres and create aurorae.",
  ],
};

export const PLANETS = [
  {
    id: "mercury",
    name: "Mercury",
    type: "Terrestrial planet",
    tagline: "A scorched messenger racing closest to the Sun.",
    color: "#9a9590",
    accent: "#c9c3bb",
    texture: `${TEX}/mercurymap.jpg`,
    surface:
      "radial-gradient(circle at 22% 30%, #b8b3ab 0 3%, transparent 7%), radial-gradient(circle at 72% 22%, #6f6a64 0 2.5%, transparent 6%), radial-gradient(circle at 58% 70%, #7d7770 0 3%, transparent 7%), radial-gradient(circle at 36% 78%, #5c5854 0 2.5%, transparent 6%), radial-gradient(circle at 82% 58%, #9a9590 0 3%, transparent 8%), radial-gradient(circle at 35% 32%, #c4bfb6 0 30%, #8a8580 62%, #3c3936 100%)",
    diameterKm: 4879,
    mass: "0.055 Earths",
    dayLength: "176 Earth days",
    year: "88 Earth days",
    distance: "0.39 AU",
    gravity: "0.38 g",
    temperature: "−180°C to 430°C",
    moons: 0,
    discovered: "Prehistoric",
    orbitRadius: 118,
    size: 22,
    period: 7.2,
    phase: 0.7,
    description:
      "The smallest planet and the fastest. Mercury is a cratered world of extremes: days hot enough to melt lead, nights cold enough to freeze nitrogen. It has almost no atmosphere to hold heat, and a massive iron core that makes up most of its interior.",
    facts: [
      "A year on Mercury is shorter than two of its solar days.",
      "It has water ice in permanently shadowed craters near the poles.",
      "Its orbit is the most eccentric of the eight planets.",
    ],
    satellites: [],
  },
  {
    id: "venus",
    name: "Venus",
    type: "Terrestrial planet",
    tagline: "Earth’s veiled twin, wrapped in a furnace.",
    color: "#d4a057",
    accent: "#f0c888",
    texture: `${TEX}/venusmap.jpg`,
    surface:
      "radial-gradient(circle at 30% 28%, #ffe2a8 0 10%, transparent 22%), radial-gradient(circle at 60% 70%, #b86b28 0 18%, transparent 40%), radial-gradient(circle at 38% 36%, #f0c888 0 24%, #d4a057 55%, #7a4316 100%)",
    diameterKm: 12104,
    mass: "0.815 Earths",
    dayLength: "243 Earth days",
    year: "225 Earth days",
    distance: "0.72 AU",
    gravity: "0.90 g",
    temperature: "465°C",
    moons: 0,
    discovered: "Prehistoric",
    orbitRadius: 158,
    size: 32,
    period: 12.4,
    phase: 2.3,
    description:
      "Similar in size to Earth, Venus is a world gone runaway. A crushing carbon-dioxide atmosphere and sulfuric-acid clouds trap heat so completely that the surface is hotter than Mercury’s. It spins backwards, and a day there lasts longer than its year.",
    facts: [
      "Venus is the brightest natural object in the night sky after the Moon.",
      "Surface pressure is about 92 times that of Earth — like being 900 m underwater.",
      "It rotates retrograde: the Sun rises in the west and sets in the east.",
    ],
    satellites: [],
  },
  {
    id: "earth",
    name: "Earth",
    type: "Terrestrial planet",
    tagline: "The only world known to harbor life.",
    color: "#3d7ea6",
    accent: "#7ec8e3",
    texture: `${TEX}/earthmap1k.jpg`,
    surface:
      "radial-gradient(ellipse 55% 16% at 48% 34%, rgba(255,255,255,0.28) 0 35%, transparent 70%), radial-gradient(ellipse 34% 22% at 68% 52%, #2d6b3a 0 42%, transparent 68%), radial-gradient(ellipse 20% 14% at 28% 62%, #245a32 0 40%, transparent 70%), radial-gradient(circle at 36% 34%, #4aa0d8 0 26%, #1a4f88 68%, #0a1a30 100%)",
    diameterKm: 12742,
    mass: "1 Earth",
    dayLength: "23 h 56 m",
    year: "365.25 days",
    distance: "1 AU",
    gravity: "1 g",
    temperature: "−89°C to 58°C",
    moons: 1,
    discovered: "—",
    orbitRadius: 204,
    size: 34,
    period: 18,
    phase: 4.1,
    description:
      "A living marble of water, rock, and air. Earth’s magnetic field and atmosphere shield the surface from solar wind and radiation. Plate tectonics recycle the crust, the oceans store heat, and a large moon steadies the planet’s tilt — a rare, delicate arrangement.",
    facts: [
      "About 71% of the surface is covered by ocean.",
      "Earth is the densest planet in the solar system.",
      "The Moon is receding by about 3.8 cm each year.",
    ],
    satellites: [
      {
        id: "moon",
        name: "The Moon",
        color: "#c5c0b5",
        texture: `${TEX}/moonmap1k.jpg`,
        size: 12,
        orbitRadius: 92,
        period: 8.4,
        diameterKm: 3475,
        discovered: "Prehistoric",
        note: "The only other world humans have walked. Its pull raises the tides and keeps Earth’s climate relatively stable.",
      },
    ],
  },
  {
    id: "mars",
    name: "Mars",
    type: "Terrestrial planet",
    tagline: "The rusted frontier, once wetter than it looks.",
    color: "#c1440e",
    accent: "#e07a3d",
    texture: `${TEX}/marsmap1k.jpg`,
    surface:
      "radial-gradient(circle at 70% 30%, #f0a36a 0 6%, transparent 14%), radial-gradient(circle at 28% 62%, #7a2208 0 10%, transparent 20%), radial-gradient(circle at 40% 34%, #e07a3d 0 22%, #c1440e 58%, #4a1408 100%)",
    diameterKm: 6779,
    mass: "0.107 Earths",
    dayLength: "24 h 37 m",
    year: "687 Earth days",
    distance: "1.52 AU",
    gravity: "0.38 g",
    temperature: "−125°C to 20°C",
    moons: 2,
    discovered: "Prehistoric",
    orbitRadius: 252,
    size: 26,
    period: 26.5,
    phase: 5.5,
    description:
      "A cold desert world stained red by iron oxide. Ancient river valleys, lake beds, and polar ice speak of a wetter past. Today a thin carbon-dioxide atmosphere and global dust storms sweep across volcanoes taller than any on Earth, including Olympus Mons.",
    facts: [
      "A Martian day — a sol — is only 39 minutes longer than an Earth day.",
      "Olympus Mons is about 22 km high, the tallest volcano in the solar system.",
      "Both moons are likely captured asteroids.",
    ],
    satellites: [
      {
        id: "phobos",
        name: "Phobos",
        color: "#8a7a6a",
        size: 6,
        orbitRadius: 62,
        period: 4.2,
        diameterKm: 22,
        discovered: "1877",
        note: "The larger Martian moon. It orbits so close that it rises in the west and sets in the east, three times a day.",
      },
      {
        id: "deimos",
        name: "Deimos",
        color: "#a89880",
        size: 5,
        orbitRadius: 88,
        period: 9.6,
        diameterKm: 12,
        discovered: "1877",
        note: "A tiny, distant companion. From the Martian surface it appears as a bright star more than a disk.",
      },
    ],
  },
  {
    id: "jupiter",
    name: "Jupiter",
    type: "Gas giant",
    tagline: "A failed star’s grandeur, striped and storming.",
    color: "#c9a27a",
    accent: "#e8c9a0",
    texture: `${TEX}/jupitermap.jpg`,
    surface:
      "repeating-linear-gradient(96deg, #e8c9a0 0 6%, #c9a27a 6% 11%, #a87b4e 11% 15%, #d8b48a 15% 20%, #8b5a32 20% 23%), radial-gradient(circle at 68% 58%, #b44a2a 0 6%, transparent 12%)",
    diameterKm: 139820,
    mass: "318 Earths",
    dayLength: "9 h 56 m",
    year: "11.86 Earth years",
    distance: "5.20 AU",
    gravity: "2.53 g",
    temperature: "−110°C (cloud tops)",
    moons: 95,
    discovered: "Prehistoric",
    orbitRadius: 330,
    size: 72,
    period: 42,
    phase: 1.4,
    description:
      "The solar system’s giant. Jupiter is a globe of hydrogen and helium with no solid surface, wrapped in banded clouds and crowned by the Great Red Spot — a storm older than most nations. Its immense gravity shepherds asteroids and shields the inner planets from some comets.",
    facts: [
      "Jupiter has the strongest magnetic field of any planet.",
      "The Great Red Spot is large enough to swallow Earth.",
      "The four Galilean moons were the first worlds found orbiting another planet.",
    ],
    satellites: [
      {
        id: "io",
        name: "Io",
        color: "#d4c04a",
        size: 9,
        orbitRadius: 78,
        period: 5.2,
        diameterKm: 3643,
        discovered: "1610",
        note: "The most volcanic body in the solar system. Tidal flexing from Jupiter keeps its interior molten.",
      },
      {
        id: "europa",
        name: "Europa",
        color: "#d8cfc0",
        size: 8.5,
        orbitRadius: 104,
        period: 8.1,
        diameterKm: 3122,
        discovered: "1610",
        note: "An ice shell over a global ocean — one of the best places to look for life beyond Earth.",
      },
      {
        id: "ganymede",
        name: "Ganymede",
        color: "#8b7d6b",
        size: 12,
        orbitRadius: 134,
        period: 12.4,
        diameterKm: 5268,
        discovered: "1610",
        note: "The largest moon in the solar system, bigger than Mercury, with its own magnetic field.",
      },
      {
        id: "callisto",
        name: "Callisto",
        color: "#6d6560",
        size: 11,
        orbitRadius: 168,
        period: 17.8,
        diameterKm: 4821,
        discovered: "1610",
        note: "An ancient, heavily cratered world. Its surface may be the oldest landscape in the Jovian system.",
      },
    ],
  },
  {
    id: "saturn",
    name: "Saturn",
    type: "Gas giant",
    tagline: "The ringed jewel of the outer system.",
    color: "#e0c48a",
    accent: "#f3ddb0",
    texture: `${TEX}/saturnmap.jpg`,
    surface:
      "repeating-linear-gradient(100deg, #f3ddb0 0 8%, #e0c48a 8% 13%, #c9a56a 13% 16%), radial-gradient(circle at 32% 30%, #fff4cc 0 12%, transparent 28%)",
    diameterKm: 116460,
    mass: "95 Earths",
    dayLength: "10 h 42 m",
    year: "29.45 Earth years",
    distance: "9.58 AU",
    gravity: "1.07 g",
    temperature: "−140°C (cloud tops)",
    moons: 146,
    discovered: "Prehistoric",
    orbitRadius: 410,
    size: 64,
    period: 58,
    phase: 3.8,
    hasRings: true,
    ringColor: "rgba(232, 210, 160, 0.55)",
    description:
      "Pale gold and impossibly light — Saturn would float in a bathtub large enough to hold it. Its rings are countless shards of ice and dust, spanning hundreds of thousands of kilometers yet only tens of meters thick in places. A retinue of moons includes worlds with oceans, geysers, and skies.",
    facts: [
      "Saturn is the least dense planet; its average density is less than water.",
      "The rings are made mostly of water ice, some pieces no larger than a snowflake.",
      "Titan is the only moon with a thick atmosphere.",
    ],
    satellites: [
      {
        id: "mimas",
        name: "Mimas",
        color: "#c8c2b8",
        size: 3.5,
        orbitRadius: 86,
        period: 5.4,
        diameterKm: 396,
        discovered: "1789",
        note: "Dominated by the crater Herschel, which gives it a startling resemblance to the Death Star.",
      },
      {
        id: "enceladus",
        name: "Enceladus",
        color: "#e8e6e0",
        size: 4,
        orbitRadius: 112,
        period: 8.8,
        diameterKm: 504,
        discovered: "1789",
        note: "Ice geysers at the south pole spray an underground ocean into space, feeding Saturn’s E ring.",
      },
      {
        id: "titan",
        name: "Titan",
        color: "#c9a36b",
        size: 12,
        orbitRadius: 148,
        period: 13.6,
        diameterKm: 5149,
        discovered: "1655",
        note: "Larger than Mercury. Rivers and lakes of liquid methane run under an orange nitrogen sky.",
      },
      {
        id: "iapetus",
        name: "Iapetus",
        color: "#6a5a4a",
        size: 5,
        orbitRadius: 186,
        period: 20.4,
        diameterKm: 1469,
        discovered: "1671",
        note: "Two-faced: one hemisphere is as dark as coal, the other as bright as snow.",
      },
    ],
  },
  {
    id: "uranus",
    name: "Uranus",
    type: "Ice giant",
    tagline: "An ice giant rolling on its side.",
    color: "#7ec8c8",
    accent: "#b8ecec",
    texture: `${TEX}/uranusmap.jpg`,
    surface:
      "radial-gradient(circle at 30% 28%, #e8ffff 0 10%, transparent 22%), radial-gradient(circle at 38% 36%, #b8ecec 0 24%, #7ec8c8 58%, #2b6a6e 100%)",
    diameterKm: 50724,
    mass: "14.5 Earths",
    dayLength: "17 h 14 m",
    year: "84 Earth years",
    distance: "19.2 AU",
    gravity: "0.89 g",
    temperature: "−195°C",
    moons: 28,
    discovered: "1781",
    orbitRadius: 478,
    size: 48,
    period: 74,
    phase: 5.9,
    hasRings: true,
    ringColor: "rgba(180, 220, 220, 0.35)",
    ringTilt: 78,
    description:
      "A pale cyan world of water, ammonia, and methane ices. Uranus spins on a tilt of 98 degrees, as if knocked over — summers and winters last 21 years. Faint rings and a family of icy moons circle a planet so cold that its cloud tops are among the chilliest in the solar system.",
    facts: [
      "Uranus was the first planet discovered with a telescope, by William Herschel.",
      "Its extreme tilt likely came from a colossal ancient collision.",
      "Methane in the atmosphere absorbs red light, leaving the planet blue-green.",
    ],
    satellites: [
      {
        id: "miranda",
        name: "Miranda",
        color: "#b0aaa0",
        size: 3.5,
        orbitRadius: 72,
        period: 5.8,
        diameterKm: 472,
        discovered: "1948",
        note: "A patchwork of cliffs and coronae, as if the moon were broken and reassembled.",
      },
      {
        id: "ariel",
        name: "Ariel",
        color: "#c5c8c4",
        size: 4.5,
        orbitRadius: 98,
        period: 8.6,
        diameterKm: 1158,
        discovered: "1851",
        note: "One of the brightest Uranian moons, scored by long canyons and smooth plains.",
      },
      {
        id: "titania",
        name: "Titania",
        color: "#9aa0a0",
        size: 6,
        orbitRadius: 128,
        period: 12.2,
        diameterKm: 1578,
        discovered: "1787",
        note: "The largest moon of Uranus, with fault valleys that hint at a warmer, more active past.",
      },
      {
        id: "oberon",
        name: "Oberon",
        color: "#7a756c",
        size: 5.5,
        orbitRadius: 160,
        period: 16.4,
        diameterKm: 1523,
        discovered: "1787",
        note: "An ancient, cratered outer moon with a mountain that may rise 6 km above the surface.",
      },
    ],
  },
  {
    id: "neptune",
    name: "Neptune",
    type: "Ice giant",
    tagline: "The deep-blue world at the edge of the planets.",
    color: "#2f5fbb",
    accent: "#6a9dff",
    texture: `${TEX}/neptunemap.jpg`,
    surface:
      "radial-gradient(circle at 28% 26%, #9ec6ff 0 10%, transparent 20%), radial-gradient(circle at 70% 64%, #163a86 0 16%, transparent 32%), radial-gradient(circle at 40% 34%, #6a9dff 0 22%, #2f5fbb 60%, #0b1c4a 100%)",
    diameterKm: 49244,
    mass: "17.1 Earths",
    dayLength: "16 h 6 m",
    year: "164.8 Earth years",
    distance: "30.1 AU",
    gravity: "1.14 g",
    temperature: "−200°C",
    moons: 16,
    discovered: "1846",
    orbitRadius: 540,
    size: 46,
    period: 90,
    phase: 2.6,
    description:
      "Found by mathematics before it was seen. Neptune is a restless ice giant with the fastest winds measured on any planet — supersonic jets that race around a methane-blue atmosphere. Its largest moon, Triton, orbits backwards and weeps nitrogen geysers.",
    facts: [
      "Neptune was predicted from irregularities in Uranus’s orbit before anyone spotted it.",
      "Winds can exceed 2,000 km/h.",
      "It has completed only one orbit around the Sun since its discovery in 1846.",
    ],
    satellites: [
      {
        id: "proteus",
        name: "Proteus",
        color: "#6e6a68",
        size: 4,
        orbitRadius: 86,
        period: 6.4,
        diameterKm: 420,
        discovered: "1989",
        note: "A dark, lumpy inner moon, one of the largest irregularly shaped bodies in the solar system.",
      },
      {
        id: "triton",
        name: "Triton",
        color: "#c8b8b0",
        size: 7,
        orbitRadius: 124,
        period: 11.8,
        diameterKm: 2707,
        discovered: "1846",
        note: "A captured Kuiper Belt world. Retrograde, geologically young, and venting nitrogen into space.",
      },
      {
        id: "nereid",
        name: "Nereid",
        color: "#9a9590",
        size: 3.5,
        orbitRadius: 168,
        period: 22,
        diameterKm: 340,
        discovered: "1949",
        note: "One of the most eccentric moon orbits known — a distant wanderer on a stretched path.",
      },
    ],
  },
  {
    id: "pluto",
    name: "Pluto",
    type: "Dwarf planet",
    tagline: "A heart-shaped world in the Kuiper Belt.",
    color: "#c4a086",
    accent: "#e8c8b0",
    texture: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Pluto_in_True_Color_-_High-Res.jpg/512px-Pluto_in_True_Color_-_High-Res.jpg",
    surface:
      "radial-gradient(circle at 58% 42%, #f0c8b4 0 10%, transparent 18%), radial-gradient(circle at 30% 68%, #7a5a4a 0 12%, transparent 22%), radial-gradient(circle at 40% 36%, #e8c8b0 0 24%, #c4a086 58%, #5a4038 100%)",
    diameterKm: 2377,
    mass: "0.002 Earths",
    dayLength: "6.4 Earth days",
    year: "248 Earth years",
    distance: "39.5 AU",
    gravity: "0.06 g",
    temperature: "−226°C",
    moons: 5,
    discovered: "1930",
    orbitRadius: 600,
    size: 18,
    period: 112,
    phase: 0.35,
    dwarf: true,
    description:
      "Once the ninth planet, now the most famous dwarf. Pluto is a binary dance with Charon, its huge moon. Nitrogen glaciers flow across a heart-shaped plain called Tombaugh Regio, and a thin atmosphere stands up when the world is nearer the Sun.",
    facts: [
      "Pluto and Charon orbit a point in space between them — a true double system.",
      "New Horizons flew by in 2015 and found mountains of water ice and a surprisingly young surface.",
      "Its orbit is tilted and eccentric, sometimes closer to the Sun than Neptune.",
    ],
    satellites: [
      {
        id: "charon",
        name: "Charon",
        color: "#8a8088",
        size: 6,
        orbitRadius: 78,
        period: 9.2,
        diameterKm: 1212,
        discovered: "1978",
        note: "Half Pluto’s diameter. The two are tidally locked, always showing each other the same face.",
      },
      {
        id: "nix",
        name: "Nix",
        color: "#d0c8c0",
        size: 3,
        orbitRadius: 112,
        period: 14.6,
        diameterKm: 50,
        discovered: "2005",
        note: "A small, bright irregular moon named for the Greek goddess of night.",
      },
      {
        id: "hydra",
        name: "Hydra",
        color: "#c8c0b4",
        size: 3,
        orbitRadius: 146,
        period: 20,
        diameterKm: 51,
        discovered: "2005",
        note: "The outermost of Pluto’s small moons, tumbling as it circles the binary pair.",
      },
    ],
  },
];

export function getBody(id) {
  if (id === "sun") return SUN;
  return PLANETS.find((p) => p.id === id) ?? null;
}
